name: mg
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dashboard:
  #   git:
  #     url: git@github.com:Biogasbottle/mgvison_dashboard.git
  #     ref: master
  # monitor:
  #   git:
  #     url: git@github.com:Biogasbottle/monitor.git
  #     ref: master
  # protos_dart:
  #   git:
  #     url: git@github.com:Biogasbottle/MgVison_protos_dart.git
  #     ref: main
  monitor:
    path: ../monitor
  dashboard:
    path: ../dashboard

  protos_dart:
    path: ../protos_dart
  commond:
    path: ../commond
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
