name: testau
on:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run your script
        run: |
          # Build your project
          # ...
          git config --global user.email "22749035@qq.com"
          git config --global user.name "myhearton"
          git config --global user.password  "${{ secrets.PAT_ALL }}"
          git clone --mirror git@github.com:Biogasbottle/mg.git /home/runner/.pub-cache/_temp/dirJUXNAH
