name: testau
on:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run your script
        run: |
          echo "host: ${{ secrets.KNOWN_HOSTS  }}"
          git clone --mirror git@github.com:Biogasbottle/monitor.git /home/runner/.pub-cache/_temp/dirJUXNAH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
